#!/usr/bin/env bun
/**
 * Generates README.md from data/certifications.yaml.
 * README.md is always generated — never hand-edit it.
 */

interface Cert {
  id: string;
  name: string;
  org: string;
  category: string;
  focus: string;
  format: string | null;
  level: string | null;
  cost_usd: number | null;
  prerequisites: string | null;
  url: string;
  status: string | null;
  launched: string | number | null;
  last_verified: string;
  notes: string | null;
}

const CATEGORIES: Record<string, { title: string; blurb: string }> = {
  offensive: {
    title: "Offensive AI Security / Red Teaming",
    blurb: "Hands-on attacking of AI systems: prompt injection, model exploitation, AI/ML pentesting.",
  },
  defensive: {
    title: "Defensive AI Security / Engineering",
    blurb: "Securing AI systems, platforms, and pipelines from the builder/defender side.",
  },
  governance: {
    title: "AI Governance, Risk & Audit",
    blurb: "Governing, auditing, and managing risk of AI systems — frameworks, law, and assurance.",
  },
  "management-systems": {
    title: "AI Management Systems (ISO/IEC 42001)",
    blurb: "Auditing and implementing AI management systems against ISO/IEC 42001.",
  },
  "vendor-ai": {
    title: "Cloud & Vendor AI Certifications",
    blurb: "Platform AI certifications — not security-specific, but the substrate AI security work runs on.",
  },
};

const root = new URL("..", import.meta.url).pathname;
const yamlText = await Bun.file(`${root}data/certifications.yaml`).text();
const certs = Bun.YAML.parse(yamlText) as Cert[];

// Field completeness check (ISC-23)
const required = ["id", "name", "org", "category", "focus", "url", "status", "last_verified"] as const;
const incomplete = certs.filter((c) => required.some((f) => c[f] == null || c[f] === ""));
if (incomplete.length > 0) {
  console.error(`INCOMPLETE ENTRIES: ${incomplete.map((c) => c.id).join(", ")}`);
  process.exit(1);
}

const fmtCost = (c: Cert) => (c.cost_usd == null ? "—" : `$${c.cost_usd.toLocaleString("en-US")}`);
const fmt = (v: string | number | null | undefined) => (v == null || v === "" ? "—" : String(v));

const rows = (list: Cert[]) =>
  list
    .sort((a, b) => a.org.localeCompare(b.org) || a.name.localeCompare(b.name))
    .map(
      (c) =>
        `| [${c.name}](${c.url}) | ${c.org} | ${c.focus} | ${fmt(c.format)} | ${fmt(c.level)} | ${fmtCost(c)} | ${fmt(c.status)} | ${c.last_verified} |`,
    )
    .join("\n");

const sections = Object.entries(CATEGORIES)
  .map(([key, meta]) => {
    const list = certs.filter((c) => c.category === key);
    if (list.length === 0) return "";
    return `## ${meta.title}

${meta.blurb}

| Certification | Org | Focus | Format | Level | Cost | Status | Verified |
|---|---|---|---|---|---|---|---|
${rows(list)}
`;
  })
  .filter(Boolean)
  .join("\n");

const today = new Date().toISOString().slice(0, 10);

const readme = `# AI Security Certifications

A living registry of AI security, AI governance, and adjacent vendor AI certifications.
**${certs.length} certifications tracked.** Generated ${today} — do not edit this file by hand; edit \`data/certifications.yaml\` and run \`bun run generate\`.

Refreshes are run by the maintainer, by hand, following the protocol in \`UPDATING.md\`. There is no automation in this repo and no fixed schedule, so the **Verified** column on each row is the authority for how current that entry is.

${sections}
---

*Costs are list prices in USD at last verification; member/bundle pricing often differs. "—" means not published or not yet verified.*
`;

await Bun.write(`${root}README.md`, readme);
console.log(`README.md generated: ${certs.length} certifications across ${Object.keys(CATEGORIES).length} categories.`);
